name: proyecto_moviles
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
    #firebase
  firebase_core: ^3.8.0
  cloud_firestore:
  #mapa
  google_maps_flutter: ^2.0.6
  #esta ayuda a la ubicacion del mapa
  geocoding: ^2.0.5
  #para ver la unbicacion actual
  geolocator: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
