// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASDv04toaO153ZDeHldz4mR1wtuiONVzo',
    appId: '1:979154191903:web:bf49241672f0ffc03df72a',
    messagingSenderId: '979154191903',
    projectId: 'proyecto-m1603-a786a',
    authDomain: 'proyecto-m1603-a786a.firebaseapp.com',
    storageBucket: 'proyecto-m1603-a786a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqAFfgldsAsCrrIUkM9WF5CZAk8pvMpLA',
    appId: '1:979154191903:android:cdb3d6b8ea9739c63df72a',
    messagingSenderId: '979154191903',
    projectId: 'proyecto-m1603-a786a',
    storageBucket: 'proyecto-m1603-a786a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvgaFF7LDMilBta3bs7yGcx30C1bjXPBI',
    appId: '1:979154191903:ios:491e476b79bffced3df72a',
    messagingSenderId: '979154191903',
    projectId: 'proyecto-m1603-a786a',
    storageBucket: 'proyecto-m1603-a786a.firebasestorage.app',
    iosBundleId: 'com.example.proyectoMoviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvgaFF7LDMilBta3bs7yGcx30C1bjXPBI',
    appId: '1:979154191903:ios:491e476b79bffced3df72a',
    messagingSenderId: '979154191903',
    projectId: 'proyecto-m1603-a786a',
    storageBucket: 'proyecto-m1603-a786a.firebasestorage.app',
    iosBundleId: 'com.example.proyectoMoviles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASDv04toaO153ZDeHldz4mR1wtuiONVzo',
    appId: '1:979154191903:web:152e1fe18c1cf1bd3df72a',
    messagingSenderId: '979154191903',
    projectId: 'proyecto-m1603-a786a',
    authDomain: 'proyecto-m1603-a786a.firebaseapp.com',
    storageBucket: 'proyecto-m1603-a786a.firebasestorage.app',
  );
}
